export const API_BASE_URL = 'http://localhost:3000/api';

export const ESTADOS_ENTREVISTA = {
  PROGRAMADA: 'PROGRAMADA',
  REALIZADA: 'REALIZADA',
  CANCELADA: 'CANCELADA',
  PENDIENTE: 'PENDIENTE',
};